// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Addon struct {
	ID                int32              `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Summary           pgtype.Text        `json:"summary"`
	AuthorName        pgtype.Text        `json:"author_name"`
	AuthorID          pgtype.Int4        `json:"author_id"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	PrimaryCategoryID pgtype.Int4        `json:"primary_category_id"`
	Categories        []int32            `json:"categories"`
	GameVersions      []string           `json:"game_versions"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt     pgtype.Timestamptz `json:"last_updated_at"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
	IsHot             pgtype.Bool        `json:"is_hot"`
	HotUntil          pgtype.Timestamptz `json:"hot_until"`
	Status            pgtype.Text        `json:"status"`
	DownloadCount     pgtype.Int8        `json:"download_count"`
	ThumbsUpCount     pgtype.Int4        `json:"thumbs_up_count"`
	PopularityRank    pgtype.Int4        `json:"popularity_rank"`
	Rating            pgtype.Numeric     `json:"rating"`
	LatestFileDate    pgtype.Timestamptz `json:"latest_file_date"`
}

type Category struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ParentID pgtype.Int4 `json:"parent_id"`
	IconUrl  pgtype.Text `json:"icon_url"`
}

type Snapshot struct {
	ID             int64              `json:"id"`
	AddonID        int32              `json:"addon_id"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	DownloadCount  int64              `json:"download_count"`
	ThumbsUpCount  pgtype.Int4        `json:"thumbs_up_count"`
	PopularityRank pgtype.Int4        `json:"popularity_rank"`
	Rating         pgtype.Numeric     `json:"rating"`
	LatestFileDate pgtype.Timestamptz `json:"latest_file_date"`
}
