# .golangci.yml
version: "2"

linters:
  default: standard
  enable:
    - gosec        # Security checks
    - goconst      # Repeated strings that could be constants
    - gocyclo      # Cyclomatic complexity
    - misspell     # Spelling mistakes
    - unconvert    # Unnecessary type conversions
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gosec:
      severity: medium
      confidence: medium

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  fix: false

run:
  timeout: 5m
  tests: true
  build-tags: []
  concurrency: 4

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
